### ISSUE TITLE
js, css not loading on cot.ubuea.cm

### ISSUE THREAD

**Issue by bosz** [wadleo/cot-website#5]
All the css and js files are not loading on the official page.

Check it

**Comment by katchoua** [comment]
This is not yet the official url of the page because the project is still ongoing...still to be sub-domained under ubuea.cm but you can take a look at it here: http://eaphysud.org/cot/public/

**Comment by bosz** [comment]
Ok. 

In that case, put a coming soon page/template cos current page on cot.ubuea.cm has a broken css and js files. 

I propose you put a coming soon page on cot.ubuea.cm. 

Regards, Fongoh

**Comment by katchoua** [comment]
Cool, it will be considered.
Thanks a lot @bosz
